### ISSUE TITLE
Block Collision

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#66] opened 2021-02-07 07:23 UTC
**Is your enhancement related to a problem? Please describe.**  
Im struggling with lag causing people to destroy their vehicles so i wan't block collision to not count but to be able to shoot/attack vehicles with weapons that affect the health.

**Describe the solution you'd like**  
Add a no block collision config and allow projectile/melee damage to vehicles.

**Comment by stijnb1234** [comment] 2021-02-08 11:25
Duplicate of #63

**Closed by stijnb1234** 2021-02-08 11:25 UTC
Labels: Enhancement
