### ISSUE TITLE
Hold-able / Place cars | Transfer-Ownership

### ISSUE THREAD

**Issue by Sockings** [VolmitSoftware/VehiclesPlus#84] opened 2021-03-14 05:30 UTC
**Is your feature request related to a problem? Please describe.**  
No, I feel like this request would be good for roleplay.

**Describe the solution you'd like**  
You buy a car, and it'll be put in your garage, already a thing, but you should make it where you can put it in your hand and you can right click to place the car, along with something in the UI to pick it back up. You can call the car back to the garage removing the item and putting it back in the garage, making it re-spawnable / replacable! (This is if they leave their car in the middle of the street somewhere)

Along with this, you should add "transfer" ownership if this isn't already a thing, (sorry if it is.) allowing players to buy(scam) other users for in-game currency! Doing this, you should make it a chat command /prefix transfer {username} and making there a confirm thing afterword's, /prefix transfer confirm.

**Describe alternatives you've considered**  
I've wrote all my suggestions above- if this is meant for something else, I'll reply with an answer.

**Additional context**  
None, imagine it, sorry.

**Comment by stijnb1234** [comment] 2021-03-27 08:53
Duplicate of #74

**Closed by stijnb1234** 2021-03-27 08:53 UTC
Labels: Feature Request
