### ISSUE TITLE
Allow custom models for vehicles

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#80] opened 2021-03-09 19:55 UTC
**Is your enhancement related to a problem? Please describe.**  
I believe that the plugin should support usage of custom models in order to decrease lag.

**Describe the solution you'd like**  
Allow custom model data items on vehicles.

**Additional context**

**Comment by relavis** [comment] 2021-03-09 20:21
Duplicate of #34

**Closed by relavis** 2021-03-09 20:21 UTC
Labels: Enhancement
