### ISSUE TITLE
Bug Report - Going through blocks

### ISSUE THREAD

**Issue by SatireShadow** [VolmitSoftware/VehiclesPlus#79] opened 2021-03-09 19:53 UTC
**Describe the bug**  
When driving on terrains, slabs, you can at times fall through certain blocks depending on your speed or even at times drive through entire walls. 

**To Reproduce**  
1. Go to ur car
2. Enter  it
3. drive around on slabs, open terrain, or try to drive through walls. It seems to primarily be an issue with new blocks and not full blocks like fences, stairs, slabs.
4. See your car phase through blocks.

**Expected behavior**  
It is expected that one could drive up and down these blocks.

**Screenshots or Video Recordings**  
If applicable, add screenshots or video recordings to help explain your problem.
I took these on the spot after driving in circles in resource world for about 10 seconds.
https://imgur.com/a/6h16UrR

**Server and Plugin Information**
 - Installed plugins: https://imgur.com/a/sXugo6x (I have a ton but I also saw others with this issue on discord)
 - VehiclesPlus Version: 2.2.6
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: Purpur 1.16.5 but it happened in spigot and paper aswell.
 - Operating System (if applicable): Java 11

**Additional context**  
Add any other context about the problem here, server timings reports, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by stijnb1234** [comment] 2021-03-10 12:44
+1, confirmed.

**Comment by stijnb1234** [comment] 2021-03-14 15:04
This is related to setting an incorrect hitbox. A hitbox visualizer can maybe solve this issue.

**Comment by SatireShadow** [comment] 2021-03-16 21:22
> This is related to setting an incorrect hitbox. A hitbox visualizer can maybe solve this issue. 

What does this mean? Is it an issue with my car config?

**Comment by stijnb1234** [comment] 2021-03-17 06:26
Probably it is. I won't close this issue before I now for sure. I'm testing with a hitbox visualizer.

**Closed** 2021-03-27 08:34 UTC
Labels: Bug, Won't Add

**Comment by stijnb1234** [comment] 2021-03-27 12:02
*(Issue is caused by misconfiguration, not by our source. #86 should make it easier to setup the hitbox correctly)*
